### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by johntom** [mcollina/fastify-auth-mongo-jwt#3]
Hi,
I get the following error on:
win 10
node 10.15.3
npm 6..4.1

npm i @matteo.collina/fastify-auth-mongo-jwt
At line:1 char:7
+ npm i @matteo.collina/fastify-auth-mongo-jwt
+       ~~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@matteo' can be used only as an
argument to a command. To reference variables in an expression use '$matteo'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted

**Comment by mcollina** [comment]
Which terminal are you using? This is a scoped package, and it should work this way.

**Comment by johntom** [comment]
Same error from 1 & 2 
1) Administrator Windows PowerShell
2) as a terminal from VS Code
3) Administrator Command Prompt dumps error C:\Users\john\AppData\Roaming\npm-cache\_logs
'C:\Frameworks\Fastify\gen\demo1\node_modules\@matteo.collina\fastify-auth-mongo-jwt'
44 verbose cwd C:\Frameworks\Fastify\gen\demo1
45 verbose Windows_NT 10.0.17763
46 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@matteo.collina/fastify-auth-mongo-jwt"
47 verbose node v10.15.3
48 verbose npm  v6.4.1
49 error path C:\Frameworks\Fastify\gen\demo1\node_modules\@matteo.collina\fastify-auth-mongo-jwt
50 error code ENOENT
51 error errno -4058
52 error syscall access
53 error enoent ENOENT: no such file or directory, access 'C:\Frameworks\Fastify\gen\demo1\node_modules\@matteo.collina\fastify-auth-mongo-jwt'
54 error enoent This is related to npm not being able to find a file.
55 verbose exit [ -4058, true ]

**Comment by johntom** [comment]
Lost these 2 lines when pasting
42 warn demo1@1.0.0 No repository field.
43 verbose stack Error: ENOENT: no such file or directory, access

**Comment by mcollina** [comment]
can you try using `cmd.exe`, this looks like an npm issue with powershell.

**Comment by johntom** [comment]
Administrator Command Prompt dumps error on install
C:\Users\john\AppData\Roaming\npm-cache_logs
'C:\Frameworks\Fastify\gen\demo1\node_modules@matteo.collina
\fastify-auth-mongo-jwt'
42 warn demo1@1.0.0 No repository field.
43 verbose stack Error: ENOENT: no such file or directory, access
44 verbose cwd C:\Frameworks\Fastify\gen\demo1
45 verbose Windows_NT 10.0.17763
46 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Program
Files\nodejs\node_modules\npm\bin\npm-cli.js" "i"
"@matteo.collina/fastify-auth-mongo-jwt"
47 verbose node v10.15.3
48 verbose npm v6.4.1
49 error path C:\Frameworks\Fastify\gen\demo1\node_modules@matteo.collina
\fastify-auth-mongo-jwt
50 error code ENOENT
51 error errno -4058
52 error syscall access
53 error enoent ENOENT: no such file or directory, access
'C:\Frameworks\Fastify\gen\demo1\node_modules@matteo.collina
\fastify-auth-mongo-jwt'
54 error enoent This is related to npm not being able to find a file.
55 verbose exit [ -4058, true ]

**Comment by johntom** [comment]
Changing from power shell to cmd fixed install
