### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by johntom** [mcollina/fastify-auth-mongo-jwt#5]
My fastify skills have improved much over last few days and love how readable the code is. I used my own jwt plugin and auth service as I always got the following when testing the following endpoint http://localhost:3000/login using  fastify-auth-mongo-jwt and postman as client. Very curious as to what I might be doing wrong. 
 setting raw body 
```
{
    "username" : "test", 
     "password" : "test"
}
```
results
```
  {
    "statusCode": 404,
    "error": "Not Found",
    "message": "Not Found"
}
```
auth.js plugin
```

//POST /signup
//POST LOGIN
'use strict'

const Fastify = require('fastify')
const AuthMongoJwt = require('@matteo.collina/fastify-auth-mongo-jwt')
const fp = require('fastify-plugin')
const app = Fastify()

module.exports = fp(async (fastify, opts) => {
// this defines const users = app.mongo.db.collection('users')
app.register(AuthMongoJwt, {
  auth: {
    secret: 'thisisalongsecretjustfortests'
  },
  mongodb: {
    url: 'mongodb://localhost:27017/course',
   w:1,
    useNewUrlParser: true
  }
})
//w: 1,
app.register(async function (app, opts) {
  app.addHook('preHandler', function (req, reply) {
    return req.jwtVerify()
  })

  app.get('/username', async function (req, reply) {
    return req.user.username
  })
}, { prefix: '/protected' })
})


```

```

**Comment by mcollina** [comment]
I’m very curious as well :). How are you running the above snippet? It seems you are not hitting any route.

**Comment by johntom** [comment]
All other routes are working fine just not the routes frrom this repo.
Perhaps you can see what I did wrong at my repo
https://github.com/johntom/Fastify-Demo2 . When complete I will leave this
public and hopefully write a blog on the journey of selecting Fastify and
learning it.
John

**Comment by mcollina** [comment]
It seems https://github.com/johntom/Fastify-Demo2/blob/master/app/plugins/auth is missing a `.js`  file extentions. It won't be loadded by fastify-autoload.

**Comment by johntom** [comment]
Sorry I took that away as Im using the jwt.js file since the auth.js file
was not working

**Comment by johntom** [comment]
simplied repo demonstrating end point not htting the login route.
https://github.com/johntom/Fastify-Demo2A

**Comment by mcollina** [comment]
You need to replace `app` with `fastify` in https://github.com/johntom/Fastify-Demo2A/blob/ed2f2a30bf5b9b6e4a233fa3eef96c3e3e138798/app/plugins/auth.js#L16.
Essentially you are creating two fastify instances, and not starting one at all.

**Comment by johntom** [comment]
Thanks. it explains why my jwt.js worked and I had the feeling it was going
to be stupid simple.
John
